// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"

void ReturnToMenu(lv_event_t * e)
{
	// Your code here
}

void OpenClock(lv_event_t * e)
{
	// Your code here
}
