// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "../ui.h"

// COMPONENT buttonround

lv_obj_t *ui_buttonround_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_buttonround;
cui_buttonround = lv_btn_create(comp_parent);
lv_obj_set_width( cui_buttonround, 65);
lv_obj_set_height( cui_buttonround, 65);
lv_obj_set_x( cui_buttonround, 0 );
lv_obj_set_y( cui_buttonround, -45 );
lv_obj_set_align( cui_buttonround, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( cui_buttonround, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_buttonround, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONROUND_NUM);
children[UI_COMP_BUTTONROUND_BUTTONROUND] = cui_buttonround;
lv_obj_add_event_cb(cui_buttonround, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_buttonround, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_buttonround_create_hook(cui_buttonround);
return cui_buttonround; 
}

