// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "../ui.h"
#include <stdio.h>

lv_obj_t * ui_LedColor = NULL;
lv_obj_t * ui_LedColorWheel = NULL;
lv_obj_t * ui_BackButtonLed = NULL;
lv_obj_t * ui_ButtonName = NULL;
// event funtions
void ui_event_BackButtonLed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ReturnToMenu(e);
    }
}

// build funtions

void ui_LedColor_screen_init(void)
{
    ui_LedColor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LedColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LedColor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LedColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LedColorWheel = lv_colorwheel_create(ui_LedColor, true);
    lv_obj_set_width(ui_LedColorWheel, 350);
    lv_obj_set_height(ui_LedColorWheel, 350);
    lv_obj_set_align(ui_LedColorWheel, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_LedColorWheel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_LedColorWheel, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BackButtonLed = lv_btn_create(ui_LedColor);
    lv_obj_set_width(ui_BackButtonLed, 250);
    lv_obj_set_height(ui_BackButtonLed, 250);
    lv_obj_set_align(ui_BackButtonLed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtonLed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButtonLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButtonLed, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButtonLed, lv_color_hex(0x272727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtonLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_BackButtonLed, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_BackButtonLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonName = lv_textarea_create(ui_BackButtonLed);
    lv_obj_set_width(ui_ButtonName, 123);
    lv_obj_set_height(ui_ButtonName, 52);
    lv_obj_set_align(ui_ButtonName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_ButtonName, 0);
    lv_textarea_set_text(ui_ButtonName, "Back");
    lv_textarea_set_placeholder_text(ui_ButtonName, "Placeholder...");
    lv_obj_clear_flag(ui_ButtonName, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_align(ui_ButtonName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonName, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonName, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackButtonLed, ui_event_BackButtonLed, LV_EVENT_ALL, NULL);

}

void ui_LedColor_screen_destroy(void)
{
    if(ui_LedColor) lv_obj_del(ui_LedColor);

    // NULL screen variables
    ui_LedColor = NULL;
    ui_LedColorWheel = NULL;
    ui_BackButtonLed = NULL;
    ui_ButtonName = NULL;

}

void ui_LedColor_update_color(int16_t hue_delta)
{
    lv_color_hsv_t h_color=lv_colorwheel_get_hsv(ui_LedColorWheel);
    int16_t new_hue = h_color.h + hue_delta;
    if (new_hue < 0)
        new_hue = (new_hue % 360 + 360) % 360;
    else
        new_hue = new_hue % 360;
    h_color.h = new_hue;
    lv_color_t color = lv_color_hsv_to_rgb(h_color.h, h_color.s, h_color.v);
    lv_colorwheel_set_rgb(ui_LedColorWheel, color);
    lv_obj_invalidate(ui_LedColorWheel);
}
