// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern lv_obj_t * ui_Menu;
extern void ui_event_MenuRoller(lv_event_t * e);
extern lv_obj_t * ui_MenuRoller;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

