// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t *ui_Menu = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Roller1 = NULL;
// event funtions
void ui_event_Roller1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      OpenClock( e );
}
}

// build funtions

void ui_Menu_screen_init(void)
{
ui_Menu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Menu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Menu);
lv_img_set_src(ui_Image1, &ui_img_bg3_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 397
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 397
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Roller1 = lv_roller_create(ui_Menu);
lv_roller_set_options( ui_Roller1, "Clock\nTest 1\nTest 2\nTest 3\nTest 4", LV_ROLLER_MODE_INFINITE );
lv_obj_set_height( ui_Roller1, 54);
lv_obj_set_width( ui_Roller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Roller1, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Roller1, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_48, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Roller1, &ui_img_bg3_png, LV_PART_SELECTED | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);

lv_obj_add_event_cb(ui_Roller1, roller_event_cb, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
   if (ui_Menu) lv_obj_del(ui_Menu);

// NULL screen variables
ui_Menu= NULL;
ui_Image1= NULL;
ui_Roller1= NULL;

}
