// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Menu.h"
#include "screens/ui_LedColor.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * left_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * right_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opa_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * dots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * cloud_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blood2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blood1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * heart_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
