// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OpenClock(lv_event_t * e);
void roller_event_cb(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
