// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch

#include "ui.h"
#include "i2c_equipment.h"

static const char *TAG = "counter";

void OpenClock(lv_event_t * e)
{
	lv_obj_t *roller = lv_event_get_target(e);

	// Get the selected index
	uint16_t selected_index = lv_roller_get_selected(roller);
	switch(selected_index)
	{
		case 0:
			lv_disp_load_scr( ui_watch_analog);
			break;
		case 1:
		case 2:
		case 3:
		default:
			break;
	}
	
	// Your code here
}

void roller_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED) {
        // Trigger haptic feedback
        i2c_drv2605_haptic_feedback(10);

        // Optional: handle other logic, e.g., get selected option
        lv_obj_t *roller = lv_event_get_target(e);
        char buf[32];
        lv_roller_get_selected_str(roller, buf, sizeof(buf));
    }
}